{
 "title": "Tunnel Server - Prometheus Remote Write",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "INFO", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "vpnserver_api_connection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vpnserver_api_connection", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vpnserver_awcm_connection",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vpnserver_awcm_connection", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vpnserver_disk_usage_percent",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (vpnserver_disk_usage_bytes{type=\"percent\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_config_info.port",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (port) (vpnserver_config_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_config_info.tls_port_sharing",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (tls_port_sharing) (vpnserver_config_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_config_info.fips_enabled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (fips_enabled) (vpnserver_config_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_config_info.config_locked",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (config_locked) (vpnserver_config_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_cpu_cores_total",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vpnserver_cpu_cores_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vpnserver_sessions_high_water_mark",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 7, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vpnserver_sessions_high_water_mark",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_disk_usage_bytes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 10, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (vpnserver_disk_usage_bytes{type=~\"used|total\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_uptime_seconds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vpnserver_uptime_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vpnserver_start_timestamp_seconds",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vpnserver_start_timestamp_seconds * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_mfa_info.mode",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 9, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (mode) (vpnserver_mfa_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_mfa_info.is_jwt",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 13, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (is_jwt) (vpnserver_mfa_info)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_traffic_rules_total",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 17, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vpnserver_traffic_rules_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "vpnserver_certificate_expiry_timestamp_seconds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "time:YYYY-MM-DD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (type) (vpnserver_certificate_expiry_timestamp_seconds) * 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_session_failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 16, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (vpnserver_session_failures)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_traffic_rules_total_proxies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vpnserver_traffic_rules_total_proxies",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_traffic_rules_total_proxy_down",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 5, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "vpnserver_traffic_rules_total_proxy_down",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_cascade_mode",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 11, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "vpnserver_cascade_mode", "legendFormat": "__auto" }
   ]
  },
  { "title": "STAT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "vpnserver_memory_usage_bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (type) (vpnserver_memory_usage_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_cpu_usage_percent (per-core util %)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (cpu) (vpnserver_cpu_usage_percent{type=\"util\", cpu=~\"core.*\"})",
     "legendFormat": "{{cpu}}"
    }
   ]
  },
  {
   "title": "vpnserver_allowlisted_devices_total",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "vpnserver_allowlisted_devices_total",
     "legendFormat": "Current"
    },
    {
     "expr": "min_over_time(vpnserver_allowlisted_devices_total[$__range])",
     "legendFormat": "Min"
    },
    {
     "expr": "max_over_time(vpnserver_allowlisted_devices_total[$__range])",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "vpnserver_current_sessions",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (platform) (vpnserver_current_sessions)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "vpnserver_sessions_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "vpnserver_sessions_total", "legendFormat": "{{hostname}} {{ip_address}}" }
   ]
  },
  {
   "title": "vpnserver_dtls_sessions_total",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    { "expr": "vpnserver_dtls_sessions_total", "legendFormat": "{{hostname}} {{ip_address}}" }
   ]
  },
  {
   "title": "vpnserver_data_bytes_total",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (direction) (vpnserver_data_bytes_total{protocol=\"tls\"})",
     "legendFormat": "TLS {{direction}}"
    },
    {
     "expr": "sum by (direction) (vpnserver_data_bytes_total{protocol=\"dtls\"})",
     "legendFormat": "DTLS {{direction}}"
    }
   ]
  }
 ]
}