apiVersion: 1
datasources:
  -
    access: proxy
    name: Prometheus
    uid: PBFA97CFB590B2093
    type: prometheus
    url: "$__env{PROMETHEUS_SCHEME}://prometheus:9090/"
    basicAuth: true
    basicAuthUser: "$__env{PROMETHEUS_USER}"
    jsonData:
      tlsSkipVerify: true
    secureJsonData:
      basicAuthPassword: "$__env{PROMETHEUS_PASSWORD}"
